### ISSUE TITLE
Code Logic

### ISSUE THREAD

**Issue by m-abubakar-saddique** [rolandojavier/fun-with-anagrams#1]
The logic of popping out the first index element is wrong.  It will always pop the first element when it should remove matching element instead of first element. 

```
    count = 0
    for i in range(0, limit):
        if text[i+1:] and checkForAnagrams(text[i], text[i+1:]):
            final_text.pop(i - count)
            count += 1
```
This is the correct logic of removing matching anagram.

**Comment by rolandojavier** [comment]
You're missing that I first reversed the array:

```
text.reverse()
# Creating a copy of the list which will be modified,
# and will not affect the array slicing during the loop.
final_text = list(text)
```

So I'm not really popping the first element but actually the last one from the original array, that way I'm removing the matching element. 

But your logic using a counter for `final_text.pop(i - count)` instead reversing the array and just using `final_text.pop(0)` works as well.

**Comment by m-abubakar-saddique** [comment]
Test this use case:
6
code
aaagmnrs
anagrams
doce
cedo
ana

You will see the issue wth your code.
Output should be:
aaagmnrs
ana
code

**Comment by rolandojavier** [comment]
You're right! I see my error now, my code does not work if a word without an anagram is left in the `final_text` array before a word that does have an anagram because I'll be always removing the first (actually last) word in the array.

I added your fix that properly moves the index through the array and added your test case also. Thanks!
